#!/usr/bin/env Rscript
#Script 14. R script for preparing ecological predictor data

library(ggfortify)
library(dplyr)
library(tidyr)

##### Input stable isotope data #####
SI <- read.csv('XXX') #table containing stable isotope (SI) data
SI <- SI %>% group_by(Species) %>% summarise(d15N = mean(d15N),d13C = mean(d13C))
gut <- read.csv('XXX') #table containing gut length data
gut_all <- gut %>% group_by(Species) %>% summarise(gut_length = mean(gut_length), weight = mean(weight))
gut_all$ratio <- gut_all$gut_length / (gut_all$weight)^(1/3)

#Exclude Orenil, Astbur for which we do not have SI
exclude_species <- c('Astbur','Orenil')
SI <- SI[!(SI$Species %in% exclude_species),]

##### Add other morphological predictors: LPJ PC2 and oral jaw PC1 ##### 
morpho <- read.csv('XXX') #table to morphological data
morpho <- na.omit(morpho)
morpho_means = aggregate(morpho[,c(2,3)], list(LPJ$Species), mean)
SI$LPJ_PC2 <- morpho_means[match(SI$Species,morpho_means$Group.1),]$LPJ_PC2
SI$oral_PC1 <- morpho_means[match(SI$Species,morpho_means$Group.1),]$oral_PC1
SI$ratio <- gut_all[match(SI$Species,gut_all$Species),]$ratio
SI <- na.omit(SI)
SI <- as.data.frame(SI)
rownames(SI) <- SI$Species

##### Perform PCA on dietary predictors to obtain diet ecology vector ##### 
pca_SI <- prcomp(SI[,c(a,b,c)],scale=T) #select columns a, b and c (numbers) corresponding to d15N, LPJ_PC2 and gut normalised length (ratio)
diet_ecology_vector <- pca_SI$x[,1] #The diet ecology vector is the PC1 of this PCA based on dietary predictors

#Save object
saveRDS(diet_ecology_vector,paste0(path_to_output_of_integration,'diet_ecology_vector.rds'))

