#!/usr/bin/env Rscript
#Script 15. R script for testing associations between epithelial relative abundances and ecology



count_cellpop <- readRDS('XXX') #file containing the number of cells in each cell population and each species
