#!/usr/bin/env Rscript
#Script 5. R script for integration of Seurat object across species

library(Seurat)

path_to_output_of_integration <- 'XXX' #path to put the output of integration

#Read Seurat object
my.se <- readRDS(paste0(path_to_output_of_integration,'integrated_dataset.rds'))

#Filter out clusters with high fraction of mitochondrial and ribosomal reads
my.se <- subset(my.se,idents=c('1','29','16','32','33'),invert=TRUE)

#Run PCA
my.se  <- RunPCA(my.se , npcs=100, verbose = FALSE)

#Find neighbours and clusters
my.se  <- FindNeighbors(my.se , reduction = "pca", dims = 1:100)
my.se  <- FindClusters(my.se , resolution = 3)

#Check the tree of clusters, to see what's the relationship between them
dims=c(1:100)

#Run UMAP
my.se <- RunUMAP(my.se, reduction = "pca", dims = 1:100)

#Assign clusters to cell types
#Check expression of marker genes
mrk<-c("epcam","LOC100706176","fabp2","LOC100704253","LOC100703770","LOC109195983","cubn","best4","cftr","myb","LOC100697624","LOC102078463","LOC102082568","pou2f3","lrmp","scg3","neurod1","LOC102081683","LOC109202766","LOC100694706","LOC100693084","LOC102078117","prdm1","epx","LOC100707205","LOC100703242","LOC100704742","LOC100699713","LOC109204854","gata3","cd79a","plk2","LOC106096470","LOC102080222","LOC100704059","anxa1","LOC100694532","lyve1","cenpe")
mrk_names<-c("epcam","amcase-1","fabp2","tmigd1","amcase-2","cathepsin L1","cubn","best4","cftr","myb","mex3a","guanylin","muc2a","pou2f3","lrmp","scg3","neurod1","cr1","mcp1b","ppt2","c1qb","c1qc","prdm1","epx","ffar2","bcl11bb","ccl3","ccl20","ccl10","gata3","cd79a","plk2","IgM μ heavy chain-like","hbab","hbba","anxa1","col1a1","lyve1","cenpe")
DotPlot(my.se,features=mrk) + scale_x_discrete(labels=rev(mrk_names)

#Assign clusters to cell type categories
enterocytes <- WhichCells(my.se,idents=c('2','4','5','8','9','15','16','23','28','31','33','39','43','46','52'))
secretory_cells <- WhichCells(my.se,idents=c('32','37','40','41','48','51','53','54'))
monocytes <- WhichCells(my.se,idents=c('14','17','21','27','47','50','55','58','59','60'))
T_cells <- WhichCells(my.se,idents=c('0','1','3','6','7','10','11','13','19','22','24','25','26','29','30','34','42','44','45','49','57'))
B_cells <- WhichCells(my.se,idents=c('18','20','38')
mesenchymal_cells <- WhichCells(my.se,idents=c('12','56')
cycling_cells <- WhichCells(my.se,idents=c('35')
red_blood_cells <- WhichCells(my.se,idents=c('36')

my.se<-SetIdent(my.se,cells =enterocytes,value = 'absorptive epithelial cells')
my.se<-SetIdent(my.se,cells =enterocytes,value = 'non-absorptive epithelial cells')
my.se<-SetIdent(my.se,cells =enterocytes,value = 'monocytes')
my.se<-SetIdent(my.se,cells =enterocytes,value = 'T cells')
my.se<-SetIdent(my.se,cells =enterocytes,value = 'B cells')
my.se<-SetIdent(my.se,cells =enterocytes,value = 'red blood cells')
my.se<-SetIdent(my.se,cells =enterocytes,value = 'B cells')
my.se<-SetIdent(my.se,cells =enterocytes,value = 'cycling cells ')



