#!/usr/bin/env Rscript
#Script 9. R script for bulk RNA deconvolution based on scRNAseq dataset
library(Seurat)
library(scibet)
library(dplyr)
library(tibble)

##### input data #####
Matrix <- as.matrix(read.csv('Matrix.txt',sep="\t",row.names="gene"))
Matrix <- head(Matrix,-5)
path_to_output_of_transcriptome_characterisation <- 'XXX' #path to put the output of analyses in this script

#Read Seurat object
my.se <- readRDS(paste0(path_to_output_of_integration,'integrated_dataset_final.rds'))

