#!/usr/bin/env Rscript
#Script 17. R script for modelling gene expression evolution

library(scuttle)
library(dplyr)
library(reshape2)
library(phytools)
library(ape)
library(ggplot2)
library(OUwie)

##### Foregut bulk RNAseq #####
Matrix <- as.matrix(read.csv('Matrix_bulkRNAseq.txt',sep="\t",row.names="gene")) #Matrix of counts from bulk RNAseq
Matrix <- head(Matrix,-5)
Coldata <- read.table('coldata_bulkRNAseq.txt',sep='\t') #Coldata table from bulk RNAseq

#Select parts 1 and 2, remove genes with very low expression
Matrix_Foregut <- Matrix[,rownames(Coldata[Coldata$part %in% c(1,2),])]
Matrix_Foregut <- Matrix_Foregut[rowSums(Matrix_Foregut>5)>=2,]

#Transform data into log2(cpm+1)
cpm_Foregut <- calculateCPM(Matrix_Foregut)
cpm_Foregut <- log2(cpm_Foregut+1)
Coldata <- Coldata[Coldata$part %in% c(1,2),]
Coldata$specimen <- rownames(Coldata)

#Function to calculate intragroup (intraspecific) variation
intragroup_function <- function(count_matrix,coldata) {
  gene_mat <- count_matrix
  gene_long <- melt(as.matrix(gene_mat))
  colnames(gene_long) <- c("gene", "specimen", "expression")
  gene_long <- merge(gene_long, coldata, by = "specimen")
  intragroup_variation <- gene_long %>%
    group_by(gene, species) %>%
    summarise(
      Variance = var(expression, na.rm = TRUE),
      SD = sd(expression, na.rm = TRUE),
      mean = mean(expression,na.rm=TRUE),
      .groups = 'drop'
    )
  return(intragroup_variation)
}

#Run function for calculating intragroup (intraspecific) variation
intragroup_variation <- intragroup_function(cpm_Foregut,Coldata)
intragroup_variation_per_gene <- intragroup_variation %>% group_by(gene) %>% summarise(mean_SD = mean(SD, na.rm = TRUE),
                                                                               mean_mean = mean(mean, na.rm = TRUE),
                                                                                                 .groups='drop')

intragroup_variation_per_gene$RSD <- intragroup_variation_per_gene$mean_SD/intragroup_variation_per_gene$mean_mean
intragroup_variation_per_gene$RSE <- intragroup_variation_per_gene$RSD/sqrt(2)
intragroup_variation_per_gene$tissue <- 'Foregut bulkRNAseq'

#Check fit of different functions on RSE data
df <- intragroup_variation_per_gene
model_power <- nls(RSE ~ a * mean_mean^b, data = df, start = list(a = 1, b = -0.5))
model_exp <- nls(RSE ~ a * exp(-b * mean_mean), data = df, start = list(a = 1, b = 0.1))
model_hyper <- nls(RSE ~ a / (mean_mean + c), data = df, start = list(a = 1, c = 1))
AIC(model_power, model_exp, model_hyper)

#Extract a and c parameters from fit of hyperbolic function

##### scRNAseq pseudobulk from enterocytes 1 #####
cpm_Permic<-as.data.frame(readRDS('XXX/cpm_Permic.rds')) #enterocytes 1 cpm values for the 2 biological duplicates of Permic
cpm_Cphfro<-as.data.frame(readRDS('XXX/cpm_Cphfro.rds')) #enterocytes 1 cpm values for the 2 biological duplicates of Cphfro
cpm_Permic <- log2(cpm_Permic+1)
cpm_Cphfro <- log2(cpm_Cphfro+1)

#Combine the two species
cpm_Permic <- cpm_Permic[rownames(cpm_Permic) %in% rownames(cpm_Cphfro),]
cpm_Cphfro <- cpm_Cphfro[rownames(cpm_Cphfro) %in% rownames(cpm_Permic),]
cpm_Cphfro <- cpm_Cphfro[rownames(cpm_Permic),]
cpm_scRNA <- cbind(cpm_Permic,cpm_Cphfro)
coldata_scRNA <- data.frame(individual=c(1,2,3,4),species=c('Permic','Permic','Cphfro','Cphfro'),specimen=colnames(cpm_scRNA))

#Run function for calculating intragroup (intraspecific) variation
intragroup_scRNA <- intragroup_function(cpm_scRNA,coldata_scRNA)
intragroup_scRNA_per_gene <- intragroup_scRNA %>% group_by(gene) %>% summarise(mean_SD = mean(SD, na.rm = TRUE),
                                                                               mean_mean = mean(mean, na.rm = TRUE),
                                                                               .groups='drop')

intragroup_scRNA_per_gene$RSD <- intragroup_scRNA_per_gene$mean_SD/intragroup_scRNA_per_gene$mean_mean
intragroup_scRNA_per_gene$RSE <- intragroup_scRNA_per_gene$RSD/sqrt(2)
intragroup_scRNA_per_gene$tissue <- 'scRNA'

#Extract a and c parameters from fit of hyperbolic function

##### Model gene expression evolution #####
#Matrices of log(cpm) within each cell population
lograwCounts<-readRDS(paste0(path_to_output_of_integration,'logcpm_byCellType.rds'))
enterocytes1 <- lograwCounts[[1]]

#Restrict to genes expressed in at least 10% of cells to avoid genes that are only sporadically expressed
genes_Prct_CellTypes <- readRDS(paste0(path_to_output_of_integration,'genes_PrctExpr.rds'))
genes_10Prct <- lapply(genes_Prct_CellTypes, function(x) x[x$Cell_proportion > 0.1,])
enterocytes1 <- enterocytes1[,colnames(enterocytes1) %in% genes_10Prct[[1]]$Markers]

##Time-calibrated species tree
tree <- readRDS(paste0(path_to_output_of_integration,'tree_byCellType.rds'))
tree_enterocytes1 <- tree[[1]]

#Make sure order of data matches order of tree tips
enterocytes1 <- enterocytes1[tree_enterocytes1$tip.label,]

#Transform into list
data_ent1 <- lapply(seq_along(colnames((enterocytes1))), function(i) enterocytes1[,i,drop=F])
genes_ent1 <- unlist(lapply(data_ent1, function(x) colnames(x)))

#Intraspecific variation from foregut bulk RNAseq
a1 <- a #value inferred from hyperbolic fit
c1 <- c #value inferred from hyperbolic fit
SE_fitted1 <- a1 / (colMeans(enterocytes1) + c1)

#Intraspecific variation from scRNAseq enterocytes 1 pseudobulk data 
a2 <- a #value inferred from hyperbolic fit
c2 <- c #value inferred from hyperbolic fit
SE_fitted2 <- a2 / (colMeans(enterocytes1) + c2)

#Run fitContinuous
fit_BM1 <- lapply(seq_along(data_ent1), function(i) fitContinuous(dat=data_ent1[[i]],phy=tree_enterocytes1,SE=SE_fitted1[[i]]*data_ent1[[i]][,1],model='BM',ncores=10))
fit_OU1 <- lapply(seq_along(data_ent1), function(i) fitContinuous(dat=data_ent1[[i]],phy=tree_enterocytes1,SE=SE_fitted1[[i]]*data_ent1[[i]][,1],model='OU',bounds = list(alpha = c(min = exp(-500), max = 20)),ncores=10))
fit_BM2 <- lapply(seq_along(data_ent1), function(i) fitContinuous(dat=data_ent1[[i]],phy=tree_enterocytes1,SE=SE_fitted2[[i]]*data_ent1[[i]][,1],model='BM',ncores=10))
fit_OU2 <- lapply(seq_along(data_ent1), function(i) fitContinuous(dat=data_ent1[[i]],phy=tree_enterocytes1,SE=SE_fitted2[[i]]*data_ent1[[i]][,1],model='OU',bounds = list(alpha = c(min = exp(-500), max = 20)),ncores=10))

#Compare models
type <- c('bulRNA','scRNA')
fit_BM <- list(fit_BM1, fit_BM2)
fit_OU <- list(fit_OU1, fit_OU2)

aicc_bm <- lapply(fit_BM, function(x) unlist(lapply(x, function(y) y$opt$aicc)))
rate_bm <- lapply(fit_BM, function(x) unlist(lapply(x, function(y) y$opt$sigsq)))
aicc_ou <- lapply(fit_OU, function(x) unlist(lapply(x, function(y) y$opt$aicc)))
rate_ou <- lapply(fit_OU, function(x) unlist(lapply(x, function(y) y$opt$sigsq)))
alpha_ou <- lapply(fit_OU, function(x) unlist(lapply(x, function(y) y$opt$alpha)))

#Summary table of AICs and model parameters
aic_data <- lapply(seq_along(aicc_bm), function(i) data.frame(geneID = genes_ent1, BM = aicc_bm[[i]] , OU = aicc_ou[[i]],
                                                              rate_BM = rate_bm[[i]], rate_OU = rate_ou[[i]],alpha = alpha_ou[[i]],type = type[[i]]))
aic_data_all <- do.call('rbind',aic_data)
aic_data_all$best <- ifelse(aic_data_all$BM <= aic_data_all$OU, "BM", "OU")

#Introduce delta AIC
aic_data_all$delta <- aic_data_all$BM - aic_data_all$OU
aic_data_all$best2 <- 'NA'
aic_data_all[aic_data_all$delta>2,]$best2 <- 'OU' 
aic_data_all[aic_data_all$delta<(-2),]$best2 <- 'BM' 

#Save the comparative table 
saveRDS(aic_data_all,'XXX/aic.rds') 

##### Compare 1-optimum OU and 2-optima OU #####
#Paint tree to have 2 regimes
tree2 <- paintSubTree(tree_enterocytes1, node=XX, state="group_2", anc.state="group_1",stem=TRUE) #XX has to be replaced by the node indicating the second evolutionary regime (here, associated with herbivory)

data <- lapply(data_ent1, function(x) {
  data.frame(species=names(data_ent1[[i]]),
             regime = c(rep('A',XX),rep('B',YY)), #XX and YY are the number of tips following regimes A and B, respectively
             gene=data_ent1[[i]],
             se = SE_fitted1[[i]] * data_ent1[[i]][,1])
  })

fit.OU1 <- lapply(data, function(x) OUwie(tree2, x, model = "OU1", mserr = 'known', simmap.tree = TRUE))
fit.OUM <- lapply(data, function(x) OUwie(tree2, x, model = "OUM", mserr = 'known', simmap.tree = TRUE))

#These fits can then be compared gene by gene

