#!/usr/bin/env Rscript
#R script for calculating for each cell population and gene the percentage of cells within the cell population expressing the gene

library(Seurat)

#Function to calculate percentage of cells expressing genes
PrctCellExpringGene <- function(object, genes, group.by = "all"){
  if(group.by == "all"){
    prct = unlist(lapply(genes,calc_helper, object=object))
    result = data.frame(Markers = genes, Cell_proportion = prct)
    return(result)
  }
  
  else{        
    list = SplitObject(object, group.by)
    factors = names(list)
    
    results = lapply(list, PrctCellExpringGene, genes=genes)
    for(i in 1:length(factors)){
      results[[i]]$Feature = factors[i]
    }
    combined = do.call("rbind", results)
    return(combined)
  }
}

#Calculation helper function
calc_helper <- function(object,genes){
  counts = object[['RNA']]@counts
  ncells = ncol(counts)
  if(genes %in% row.names(counts)){
    sum(counts[genes,]>0)/ncells
  }else{return(NA)}
}

#Input Seurat integrated object
my.se <- readRDS(paste0(path_to_output_of_integration,'integrated_dataset_final.rds'))

#Get Seurat object for each cell population
Idents(my.se) <- my.se$CellTypes
my.se.subset <- lapply(levels(my.se$CellTypes), function(x) subset(my.se,idents=c(x)))

#Keep genes expressed in at least 2 cells in each species
genes_ToKeep <- readRDS('XXX') 

#Calculate within each cell type the percentage of cells expressing each gene
genes_Prct_CellTypes <- lapply(my.se.subset, function(x) PrctCellExpringGene(x,genes_ToKeep,group.by='all'))

#Save percentage object
saveRDS(genes_Prct_CellTypes, paste0(path_to_output_of_integration,'genes_PrctExpr.rds'))





